### ISSUE TITLE
When will the source code of AFN be released？

### ISSUE THREAD

**Issue by yfreedomliTHU** [WeiyuCheng/AFN-AAAI-20#1]
Hi, @WeiyuCheng , I'm really interested in your work(AFN) in AAAI’20. Can you release your source code?Thank you!

**Comment by WeiyuCheng** [comment]
Hello, thanks for your attention. We will try to release the code before or soon after the conference.

**Comment by WeiyuCheng** [comment]
Hello, today we have released the source codes. The issue will be closed.
