### ISSUE TITLE
关于代码的一点疑问

### ISSUE THREAD

**Issue by GongTengNewOne** [WeiyuCheng/AFN-AAAI-20#2]
你好，我在运行代码时遇到以下报错：
“”
File "./src/AFN.py", line 278, in main
    with open(tr_files[1]) as f:
IndexError: list index out of range
“”
这是为什么呢？

**Comment by WeiyuCheng** [comment]
你好，应该需要修改一下data_dir的路径，设成数据集的路径

**Comment by WeiyuCheng** [comment]
Hi, I have modified the default data_dir in AFN.py. The issue will be closed.
