### ISSUE TITLE
about the feature size

### ISSUE THREAD

**Issue by GuoshenLi** [WeiyuCheng/AFN-AAAI-20#9]
hi! it seems that the feature size of frappa dataset is 5382. And you set that to 5500. Is that ok? or can you explain a little bit about why you set to a bigger number?

**Comment by WeiyuCheng** [comment]
Hi Guoshen, we just employed a round value for convience, while only 0~5381 are used for indexing features. 
This doesn't affect the results so you can just set it to the exact feature size if you would like.
